server:
  port: 8082

spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ushanna1990/spring-resource-dev.git
          searchPaths: config/dev/resources   # Specify the path within the repo
          clone-on-start: true                # Clone the repo on startup

#Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true